apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
      - name: python-flask-app
        image: 381492022241.dkr.ecr.eu-north-1.amazonaws.com/my_repo:latest  # Replace with your ECR image URL
        ports:
        - containerPort: 5000
